-- 06_sdr_agente_enum.sql
--
-- Fecha o Gap 3 (CR-01, plano 01-09): o enum Postgres `agente_tipo_roberth`
-- (coluna `conversations_roberth.agente_atual`) so tinha 'vendedor' e
-- 'atendimento_humano'. Sem os novos valores, a sessao da Camila/Qualificador
-- nunca persiste de fato no banco — um restart do processo (ou eviction do
-- cache em memoria) faz o lead voltar a ser atendido pela Sofia (vendedora
-- do curso legado), mesmo que esteja no meio do SPIN ou ESCALADO por
-- sofrimento agudo.
--
-- Idempotente: usa a clausula "IF NOT EXISTS" do ALTER TYPE (Postgres 12+,
-- suportado pelo Supabase) — pode rodar mais de uma vez sem erro.
--
-- [BLOCKING] Esta migracao e PRE-REQUISITO para a persistencia real dos
-- novos valores em producao. O codigo das Tasks 2/3 do plano 01-09 e seguro
-- de landar ANTES desta migracao ser aplicada — `atualizarConversa` (PATCH
-- via PostgREST) engole erro de valor de enum invalido e so loga; mas o
-- valor 'qualificador'/'camila' so persiste de fato apos o enum aceitar.
--
-- IMPORTANTE — banco: aplicar no Supabase DEDICADO do SDR AUTON (env
-- `SUPABASE_DB_URL`), separado do banco em producao do Projeto Roberth.
-- Decisao do usuario, 2026-07-13 (ver .planning/STATE.md e MEMORY.md,
-- nota "Banco dedicado do SDR").
--
-- Aplicar (non-TTY safe; falha limpo se SUPABASE_DB_URL nao estiver no .env):
--   node scripts/apply-migration.mjs docs/sql/06_sdr_agente_enum.sql
--
-- NAO usar os novos valores de enum na mesma transacao em que sao
-- adicionados — Postgres nao permite `ALTER TYPE ... ADD VALUE` e o uso do
-- valor novo na mesma transacao. Por isso os 2 statements ficam separados,
-- sem bloco transacional envolvendo consumo do valor.

ALTER TYPE agente_tipo_roberth ADD VALUE IF NOT EXISTS 'qualificador';
ALTER TYPE agente_tipo_roberth ADD VALUE IF NOT EXISTS 'camila';
