services:
  discador:
    build: .
    container_name: discador-wavoip
    restart: unless-stopped
    ports:
      - "4111:4111"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
