-- SDR AUTON Health — Migration 05: NO-OP (Kiwify removido do stack)
-- Data original: 2026-05-09 | Neutralizada: 2026-07-13
--
-- Decisao do usuario (2026-07-13, quick task 260713-t0f): o SDR AUTON Health
-- NAO usa Kiwify. O webhook de confirmacao de pagamento Kiwify e legado do
-- funil do curso do ex-bot Closer "Roberth" — o SDR AUTON e um SDR
-- (qualifica + agenda call com um closer humano, nao fecha venda dentro do
-- proprio fluxo), entao nao existe "pagamento aprovado pelo Kiwify" no dominio
-- dele. O codigo (src/mastra/supabase.ts, index.ts, dashboard.ts, follow-up.ts)
-- foi limpo de toda referencia a pagamento_confirmado/kiwify_order_id/valor_pago
-- na mesma quick task.
--
-- Este arquivo original adicionava as colunas pagamento_confirmado,
-- pagamento_confirmado_em, kiwify_order_id, valor_pago em
-- auton_sdr_conversations + indices — tudo removido daqui.
--
-- Por que este arquivo continua existindo como NO-OP (em vez de ser deletado):
-- o runbook de deploy roda as migrations em ordem numerica
-- (`node scripts/apply-migration.mjs docs/sql/auton_sdr/0N_*.sql`, 01 -> 06).
-- Remover o arquivo 05 quebraria essa numeracao espelhada e o runbook do
-- usuario. Este NO-OP preserva o passo 05 na sequencia sem executar nenhum
-- DDL — zero ALTER/CREATE.

SELECT 1;
