-- SDR AUTON Health — 10_agente_default.sql (banco dedicado)
--
-- Fecha o residuo Closer no banco (CLEAN-01/CLEAN-02, plano 04-02): a coluna
-- `auton_sdr_conversations.agente_atual` tem DEFAULT 'vendedor' desde
-- 01_init.sql (era do agente Sofia/Closer). O plano 04-01 ja removeu por
-- completo o agente logico 'vendedor' do codigo (dispatcher/sessao.ts/
-- supabase.ts nunca mais escrevem ou resolvem pra 'vendedor' — o fallback
-- fail-safe e 'atendimento_humano'). Esta migracao alinha o DEFAULT da
-- coluna ao codigo, para uma linha eventualmente inserida sem valor
-- explicito de agente_atual nao reviver o residuo Closer no banco.
--
-- O QUE ESTA MIGRACAO NAO FAZ (fora de escopo, deliberado):
--   - NAO remove o valor 'vendedor' do TYPE `auton_sdr_agente_tipo` — Postgres
--     nao suporta DROP VALUE de enum sem recriar o tipo inteiro (ALTER TYPE
--     ... DROP VALUE nao existe); fazer isso exigiria criar um tipo novo,
--     migrar a coluna, dropar o antigo — risco/escopo desproporcional pra
--     limpar um residuo que nao afeta mais o comportamento do sistema.
--   - NAO altera nenhuma linha existente — so o DEFAULT de linhas futuras.
--
-- Por que e seguro/nao-bloqueante para o codigo: todo INSERT em
-- auton_sdr_conversations passa o agente explicito via criarConversa/
-- criarSessao (agenteParaEnum(agenteAtual)) — o codigo NUNCA depende do
-- DEFAULT da coluna pra funcionar corretamente, com ou sem esta migracao
-- aplicada. Este SQL e polimento de schema, nao um pre-requisito funcional.
--
-- Idempotente: `ALTER COLUMN ... SET DEFAULT` pode ser executado N vezes
-- sem erro (sempre redefine o mesmo valor).
--
-- [BLOCKING]/user_setup — o banco dedicado do SDR AUTON esta em modo
-- READ-ONLY (erro confirmado: "cannot execute CREATE TABLE/ALTER in a
-- read-only transaction", quota 402 do projeto Supabase). Aplicar somente
-- QUANDO a quota for resolvida, via:
--   node scripts/apply-migration.mjs docs/sql/auton_sdr/10_agente_default.sql

ALTER TABLE auton_sdr_conversations
  ALTER COLUMN agente_atual SET DEFAULT 'atendimento_humano';
